# Build the k8srd binary
FROM golang:1.24 as builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /k8srd ./cmd/k8srd

# Create the final image
FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=builder /k8srd .
USER 65532:65532

ENTRYPOINT ["/k8srd"]
